# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 550)

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 420, 100, 50))
        self.pushButton.setObjectName("pushButton")

        # подключаем кнопку к ф-ции buttonClickedClear
        self.pushButton.clicked.connect(self.buttonClickedClear)

        # отвечает за поиск в бд-шке
        self.lineEdit = QtWidgets.QLineEdit(
            self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 100, 30))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 85, 310, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 255, 240, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 425, 220, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 355, 460, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 425, 230, 30))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 15, 100, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label.setFont(font)
        self.label.setObjectName("label")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 10, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.buttonClickedSearch)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 65, 310, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(115, 130, 250, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 200, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 160, 155, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 240, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 230, 160, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(480, 0, 20, 550))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 300, 141, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 330, 211, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 400, 222, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 400, 245, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 100, 20))

        font = QtGui.QFont()
        font.setPointSize(10)

        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 495, 220, 30))
        self.lineEdit_10.setObjectName("lineEdit_10")

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 471, 17))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 480, 100, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.insertInDataBase)

        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 185, 240, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 185, 200, 30))
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(270, 255, 200, 30))
        self.lineEdit_9.setObjectName("lineEdit_9")

        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    # метод для очистки полей и одного лейбла

    def buttonClickedClear(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.lineEdit_8.clear()
        self.lineEdit_9.clear()
        self.lineEdit_10.clear()
        self.label_15.setText("Поля успешно очищены")

    # метод для поиска в бд
    def buttonClickedSearch(self):
        # подключение в бд
        self.con = sqlite3.connect("database.sqlite")
        self.cur = self.con.cursor()
        self.result = self.cur.execute(
            """SELECT nomer FROM Заказы""").fetchall()
        # засунул в отдельную переменную, т.к. не проходил по pep8
        paste = "Заказ не найден. Заполните все поля и нажмите 'Загрузить'"

        """циклы для поиска номера заказа. из result
        возвращается в виде [(x,)]
        """
        for self.element in self.result:

            for self.elem in self.element:

                if self.elem == int(self.lineEdit.text()):
                    self.label_15.setText("")
                    self.con.close()
                    return self.paste_values()

                else:
                    self.label_15.setText(paste)
        # закрываем бд(ОБЯЗАТЕЛЬНО)
        self.con.close()

    # метод для подстановки значений в поля

    def paste_values(self):
        self.con = sqlite3.connect("database.sqlite")
        self.cur = self.con.cursor()

        self.opisanie = self.cur.execute("""SELECT opisanie FROM Заказы
                                            WHERE nomer=?""",
                                         (self.elem,)).fetchall()

        # достаём из переменной строку и помещаем её в поле для ввода
        self.lineEdit_2.setText(*[j for i in self.opisanie for j in i])

        self.rabotaet = self.cur.execute("""SELECT rabotaet FROM Заказы
                                            WHERE nomer=?""",
                                         (self.elem,)).fetchall()

        self.lineEdit_7.setText(*[j for i in self.rabotaet for j in i])

        self.os = self.cur.execute("""SELECT os FROM Заказы
                                            WHERE nomer=?""",
                                   (self.elem,)).fetchall()

        self.lineEdit_8.setText(*[j for i in self.os for j in i])

        self.povrezhdeniya = self.cur.execute("""SELECT povrezhdeniya
                                            FROM Заказы
                                            WHERE nomer=?""",
                                              (self.elem,)).fetchall()

        self.lineEdit_3.setText(*[j for i in self.povrezhdeniya for j in i])

        self.hdd = self.cur.execute("""SELECT hdd FROM Заказы
                                            WHERE nomer=?""",
                                    (self.elem,)).fetchall()

        self.lineEdit_9.setText(*[j for i in self.hdd for j in i])

        self.obyazat = self.cur.execute("""SELECT obyazat FROM Заказы
                                            WHERE nomer=?""",
                                        (self.elem,)).fetchall()

        self.lineEdit_5.setText(*[j for i in self.obyazat for j in i])

        self.recomend = self.cur.execute("""SELECT recomend FROM Заказы
                                            WHERE nomer=?""",
                                         (self.elem,)).fetchall()

        self.lineEdit_4.setText(*[j for i in self.recomend for j in i])

        self.profilact = self.cur.execute("""SELECT profilact FROM Заказы
                                            WHERE nomer=?""",
                                          (self.elem,)).fetchall()

        self.lineEdit_6.setText(*[j for i in self.profilact for j in i])

        self.riski = self.cur.execute("""SELECT riski FROM Заказы
                                            WHERE nomer=?""",
                                      (self.elem,)).fetchall()

        self.lineEdit_10.setText(*[j for i in self.riski for j in i])

    # метод для добавления новых заказов в бд
    # тут ничего нового, просто не забываем коммитить

    def insertInDataBase(self):
        self.con = sqlite3.connect("database.sqlite")
        self.cur = self.con.cursor()
        self.proverka = self.cur.execute(
            """SELECT nomer FROM Заказы""").fetchall()
        self.count = 0

        for self.element in self.proverka:

            for self.elem in self.element:

                if self.elem == int(self.lineEdit.text()):
                    self.count += 1

        if self.count == 1:
            self.cur.execute("""UPDATE Заказы
                                SET opisanie = ?,
                                rabotaet = ?,
                                os = ?,
                                povrezhdeniya = ?,
                                hdd = ?,
                                obyazat = ?,
                                recomend = ?,
                                profilact = ?,
                                riski = ?
                                WHERE nomer = ?""",
                             (self.lineEdit_2.text(),
                                 self.lineEdit_7.text(),
                                 self.lineEdit_8.text(),
                                 self.lineEdit_3.text(),
                                 self.lineEdit_9.text(),
                                 self.lineEdit_5.text(),
                                 self.lineEdit_4.text(),
                                 self.lineEdit_6.text(),
                                 self.lineEdit_10.text(),
                                 self.lineEdit.text(), )
                             ).fetchall()
            self.con.commit()
            self.label_15.setText("Заказ был успешно обновлён")

        else:
            self.cur.execute("""INSERT INTO Заказы VALUES(
                            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                             (self.lineEdit.text(),
                                 self.lineEdit_2.text(),
                                 self.lineEdit_7.text(),
                                 self.lineEdit_8.text(),
                                 self.lineEdit_3.text(),
                                 self.lineEdit_9.text(),
                                 self.lineEdit_5.text(),
                                 self.lineEdit_4.text(),
                                 self.lineEdit_6.text(),
                                 self.lineEdit_10.text(),
                              )
                             )
            self.con.commit()
            self.label_15.setText("Заказ был успешно добавлен")
        self.con.close()

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow",
                                             "Первичный осмотр"))
        self.pushButton.setText(_translate("mainWindow",
                                           "Очистить"))
        self.label.setText(_translate("mainWindow", "Номер заказа"))
        self.pushButton_2.setText(_translate("mainWindow", "Поиск"))
        self.label_2.setText(_translate(
            "mainWindow", "1.1 <Описание характеристик компьютера>"))
        self.label_3.setText(_translate(
            "mainWindow", "1.2 <Первичное описание техники>"))
        self.label_4.setText(_translate(
            "mainWindow", "1.2.1 <Включается или нет>"))
        self.label_5.setText(_translate("mainWindow",
                                        "1.2.2 <Состояние ОС>"))
        self.label_6.setText(_translate(
            "mainWindow", "1.2.3 <Внутренние повреждения>"))
        self.label_7.setText(_translate("mainWindow",
                                        "1.2.4 <Состояние ЖД>"))
        self.label_8.setText(_translate("mainWindow",
                                        "1.3 <Диагностика>"))
        self.label_9.setText(_translate(
            "mainWindow", "1.3.1 <Обязательные работы>"))
        self.label_10.setText(_translate(
            "mainWindow", "1.3.2 <Рекомендуемые работы>"))
        self.label_11.setText(_translate(
            "mainWindow", "1.3.3 <Профилактические работы>"))
        self.label_12.setText(_translate("mainWindow",
                                         "1.3.5 <Риски>"))
        self.pushButton_3.setText(_translate("mainWindow",
                                             "Загрузить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
